version: '2'
networks:
    raft:

services:
    ca.cutter.com:
        image: hyperledger/fabric-ca:$CA_IMAGE_TAG
        container_name: ca.cutter.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cutter.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
            - FABRIC_CA_SERVER_CA_NAME=ca.cutter.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cutter.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
            - FABRIC_CA_SERVER_PORT=7054
        #command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.cutter.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk  -b admin:adminpw -d'
        command: sh -c 'fabric-ca-server start  -b admin:adminpw -d'
        volumes:
            - ../crypto-config/peerOrganizations/cutter.com/ca/:/etc/hyperledger/fabric-ca-server-config
        ports:
            - "8054:7054"
        networks:
            - raft


    couchdb.peer0-cutter.com:
        container_name: couchdb.peer0-cutter.com
        image: couchdb:$THIRD_PARTY_TOOLS_IMAGE_IAG
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        volumes:
            - ./persistent_volumes/couchdb.peer0-cutter.com/:/opt/couchdb/data
        ports:
            - "6984:5984"
        networks:
            - raft 


    peer0.cutter.com:
        container_name: peer0.cutter.com
        extends:
            file: base/docker-compose-peer-base.yaml
            service: peer-base
        environment:
            - CORE_PEER_ID=peer0.cutter.com
            - CORE_PEER_ADDRESS=peer0.cutter.com:8051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cutter.com:8051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cutter.com:8051
            - CORE_PEER_CHAINCODEADDRESS=peer0.cutter.com:8052
            - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_raft
            - CORE_PEER_LOCALMSPID=cutterMSP
            - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
            #- CORE_CHAINCODE_EXECUTETIMEOUT=300S
            #- CORE_PEER_KEEPALIVE_CLIENT_TIMEOUT=300S
            #- CORE_PEER_KEEPALIVE_DELIVERYCLIENT_TIMEOUT=300S

            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0-cutter.com:5984
            - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
            - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/cutter.com/peers/peer0.cutter.com/msp:/etc/hyperledger/fabric/msp
            - ../crypto-config/peerOrganizations/cutter.com/peers/peer0.cutter.com/tls:/etc/hyperledger/fabric/tls
            - ./persistent_volumes/peer0.cutter.com/:/var/hyperledger/production
        ports:
            - 8051:8051
            - 8053:8053
        depends_on:
            - couchdb.peer0-cutter.com
        networks:
            - raft

    cli.peer0-cutter.com:
        container_name: cli.peer0-cutter.com
        image: hyperledger/fabric-tools:$IMAGE_TAG
        tty: true
        stdin_open: true
        environment:
            - GOPATH=/opt/gopath
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            #- FABRIC_LOGGING_SPEC=DEBUG
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_PEER_ID=cli.peer0-cutter.com
            - CORE_PEER_ADDRESS=peer0.cutter.com:8051
            - CORE_PEER_LOCALMSPID=cutterMSP
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/cutter.com/peers/peer0.cutter.com/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/cutter.com/peers/peer0.cutter.com/tls/ca.crt
            - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/cutter.com/users/Admin@cutter.com/msp
            - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/supplychain.com/orderers/orderer0.supplychain.com/msp/tlscacerts/tlsca.cutter.com-cert.pem
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ../chaincodes/:/opt/gopath/src/github.com/chaincodes
            - $GOPATH/src/:/opt/gopath/src/
            - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        networks:
            - raft
