OrdererOrgs:
  - Name: Orderer
    Domain: supplychain.com
    Template:
      Count: 1
PeerOrgs:
  - Name: forestOrg
    Domain: forest.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: cutterOrg
    Domain: cutter.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: logisticsOrg
    Domain: logistics.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: manufactureOrg
    Domain: manufacture.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
